version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.18.2
    steps:
      - checkout
      - run: yarn install

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $VM_SSH_FINGERPRINT
      - run:
          name: Deploy to GCP Compute Engine
          command: |
            ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "cd /home/dino_wu/oogiri/material-dashboard-react-vite/ && sudo git pull && sudo yarn install && sudo yarn build:staging:oogiri && sudo rm -r /var/www/oogiriinfoBuild/ && sudo mv dist oogiriinfoBuild && sudo mv oogiriinfoBuild /var/www/"

  uat_deploy_pickme:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $VM_SSH_FINGERPRINT
      - run:
          name: Deploy to GCP Compute Engine
          command: |
            ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "cd /home/dino_wu/pickme/material-dashboard-react-vite/ && sudo git pull && sudo yarn install && sudo yarn build:staging:mu && sudo rm -r /var/www/pickmeBuild/ && sudo mv dist pickmeBuild && sudo mv pickmeBuild /var/www/"

  production_deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $PROD_VM_SSH_FINGERPRINT
      - run:
          name: Deploy to GCP Compute Engine
          command: |
            ssh -o StrictHostKeyChecking=no $VM_USER@$PROD_VM_IP "cd /home/dino_wu/material-dashboard-react-vite/ && sudo git pull && sudo yarn install && sudo yarn build:prod:oogiri && sudo rm -r /var/www/dist/ && sudo mv dist /var/www/"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: uat
      - uat_deploy_pickme:
          requires:
            - build
          filters:
            branches:
              only: uat-mu
      - production_deploy:
          requires:
            - build
          filters:
            branches:
              only: main
